---
# tasks file for patching

- name: Install latest patches on Ubuntu
  ansible.builtin.apt:
    name: '*'
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
    state: latest

...      