---

- hosts: master
  gather_facts: true
  become: true

  tasks:

  # Ubuntu  
  - name: Install "helm" with option --classic
    community.general.snap:
      name: helm
      classic: true    

  - name: Add a repository stable
    kubernetes.core.helm_repository:
      name: stable
      repo_url: https://charts.helm.sh/stable

  - name: Add a repository
    community.kubernetes.helm_repository:
      name: bitnami
      repo_url: https://charts.bitnami.com/bitnami

  - name: Add a repository
    community.kubernetes.helm_repository:
      name: kubernetes-dashboard
      repo_url: https://kubernetes.github.io/dashboard/  

  - name: Run helm update
    ansible.builtin.command: sudo helm repo update

...  