---
# Playbook imports for K3s cluster build

- ansible.builtin.import_playbook: ./plays/hosts.yml

- ansible.builtin.import_playbook: ./plays/patching.yml

- ansible.builtin.import_playbook: ./plays/k3s.yml

...