---
# tasks for copy

- hosts: '*'
  become: true
  tasks:

  - name: Copy hosts file with owner and permissions
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: '0644'
      remote_src: false
    when: ansible_hostname == 'k3s1'
    with_items:
      - src: ./files/hosts_k3s1
        dest: /etc/hosts

  - name: Copy hosts file with owner and permissions
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: '0644'
      remote_src: false
    when: ansible_hostname == 'k3s2'
    with_items:
      - src: ./files/hosts_k3s2
        dest: /etc/hosts

  - name: Copy hosts file with owner and permissions
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: '0644'
      remote_src: false
    when: ansible_hostname == 'k3s3'
    with_items:
      - src: ./files/hosts_k3s3
        dest: /etc/hosts
...